#!/bin/bash.exe

alias cls='echo -e "\ec\e[3J"'
alias clearall='echo -e "\ec\e[3J"'

alias "compress"="/bin/toybox.exe compress"
alias "count"="/bin/toybox.exe count"
alias "factor"="/bin/toybox.exe factor"
alias "free"="/bin/toybox.exe free"
alias "host"="/bin/toybox.exe host"
alias "link"="/bin/toybox.exe link"
alias "nc"="/bin/toybox.exe nc"
alias "netcat"="/bin/toybox.exe netcat"
alias "nl"="/bin/toybox.exe nl"
alias "shred"="/bin/toybox.exe shred"
alias "truncate"="/bin/toybox.exe truncate"
alias "uptime"="/bin/toybox.exe uptime"

export VAGRANT_DETECTED_OS="cygwin"
export GIT_PAGER="/bin/busybox.exe less -R"

alias "ar"="/bin/busybox.exe ar"
alias "awk"="/bin/busybox.exe awk"
alias "base64"="/bin/busybox.exe base64"
alias "basename"="/bin/busybox.exe basename"
alias "bunzip2"="/bin/busybox.exe bunzip2"
alias "bzcat"="/bin/busybox.exe bzcat"
alias "bzip2"="/bin/busybox.exe bzip2"
alias "cal"="/bin/busybox.exe cal"
alias "cat"="/bin/busybox.exe cat"
alias "catv"="/bin/busybox.exe catv"
alias "chat"="/bin/busybox.exe chat"
alias "chgrp"="/bin/busybox.exe chgrp"
alias "chmod"="/bin/busybox.exe chmod"
alias "chown"="/bin/busybox.exe chown"
alias "chpasswd"="/bin/busybox.exe chpasswd"
alias "chpst"="/bin/busybox.exe chpst"
alias "chroot"="/bin/busybox.exe chroot"
alias "chrt"="/bin/busybox.exe chrt"
alias "cksum"="/bin/busybox.exe cksum"
alias "clear"="/bin/busybox.exe clear"
alias "cmp"="/bin/busybox.exe cmp"
alias "comm"="/bin/busybox.exe comm"
alias "cp"="/bin/busybox.exe cp"
alias "cpio"="/bin/busybox.exe cpio"
alias "crond"="/bin/busybox.exe crond"
alias "crontab"="/bin/busybox.exe crontab"
alias "cryptpw"="/bin/busybox.exe cryptpw"
alias "cut"="/bin/busybox.exe cut"
alias "date"="/bin/busybox.exe date"
alias "dc"="/bin/busybox.exe dc"
alias "dd"="/bin/busybox.exe dd"
alias "devmem"="/bin/busybox.exe devmem"
alias "df"="/bin/busybox.exe df"
alias "diff"="/bin/busybox.exe diff"
alias "dirname"="/bin/busybox.exe dirname"
alias "dnsd"="/bin/busybox.exe dnsd"
alias "dnsdomainname"="/bin/busybox.exe dnsdomainname"
alias "dos2unix"="/bin/busybox.exe dos2unix"
alias "du"="/bin/busybox.exe du"
alias "ed"="/bin/busybox.exe ed"
alias "env"="/bin/busybox.exe env"
alias "envdir"="/bin/busybox.exe envdir"
alias "envuidgid"="/bin/busybox.exe envuidgid"
alias "expand"="/bin/busybox.exe expand"
alias "expr"="/bin/busybox.exe expr"
alias "fakeidentd"="/bin/busybox.exe fakeidentd"
alias "find"="/bin/busybox.exe find"
alias "fold"="/bin/busybox.exe fold"
alias "fsync"="/bin/busybox.exe fsync"
alias "ftpget"="/bin/busybox.exe ftpget"
alias "ftpput"="/bin/busybox.exe ftpput"
alias "fuser"="/bin/busybox.exe fuser"
alias "gawk"="/bin/busybox.exe awk"
alias "getopt"="/bin/busybox.exe getopt"
alias "groups"="/bin/busybox.exe groups"
alias "gunzip"="/bin/busybox.exe gunzip"
alias "gzip"="/bin/busybox.exe gzip"
alias "hd"="/bin/busybox.exe hd"
alias "head"="/bin/busybox.exe head"
alias "hexdump"="/bin/busybox.exe hexdump"
alias "hostid"="/bin/busybox.exe hostid"
alias "hostname"="/bin/busybox.exe hostname"
alias "httpd"="/bin/busybox.exe httpd"
alias "id"="/bin/busybox.exe id"
alias "inetd"="/bin/busybox.exe inetd"
alias "install"="/bin/busybox.exe install"
alias "iostat"="/bin/busybox.exe iostat"
alias "ipcalc"="/bin/busybox.exe ipcalc"
alias "killall"="/bin/busybox.exe killall"
alias "killall5"="/bin/busybox.exe killall5"
alias "less"="/bin/busybox.exe less"
alias "ln"="/bin/busybox.exe ln"
alias "logger"="/bin/busybox.exe logger"
alias "logname"="/bin/busybox.exe logname"
alias "logread"="/bin/busybox.exe logread"
alias "lpd"="/bin/busybox.exe lpd"
alias "lpq"="/bin/busybox.exe lpq"
alias "lpr"="/bin/busybox.exe lpr"
alias "ls"="/bin/busybox.exe ls"
alias "lsof"="/bin/busybox.exe lsof"
alias "lzcat"="/bin/busybox.exe lzcat"
alias "lzma"="/bin/busybox.exe lzma"
alias "lzop"="/bin/busybox.exe lzop"
alias "lzopcat"="/bin/busybox.exe lzopcat"
alias "makemime"="/bin/busybox.exe makemime"
alias "md5sum"="/bin/busybox.exe md5sum"
alias "mesg"="/bin/busybox.exe mesg"
alias "mkdir"="/bin/busybox.exe mkdir"
alias "mkfifo"="/bin/busybox.exe mkfifo"
alias "mknod"="/bin/busybox.exe mknod"
alias "mktemp"="/bin/busybox.exe mktemp"
alias "more"="/bin/busybox.exe more"
alias "mpstat"="/bin/busybox.exe mpstat"
alias "mt"="/bin/busybox.exe mt"
alias "mv"="/bin/busybox.exe mv"
alias "nice"="/bin/busybox.exe nice"
alias "nmeter"="/bin/busybox.exe nmeter"
alias "nohup"="/bin/busybox.exe nohup"
alias "nslookup"="/bin/busybox.exe nslookup"
alias "od"="/bin/busybox.exe od"
alias "patch"="/bin/busybox.exe patch"
alias "pgrep"="/bin/busybox.exe pgrep"
alias "pidof"="/bin/busybox.exe pidof"
alias "pipe_progress"="/bin/busybox.exe pipe_progress"
alias "pkill"="/bin/busybox.exe pkill"
alias "popmaildir"="/bin/busybox.exe popmaildir"
alias "printenv"="/bin/busybox.exe printenv"
alias "pscan"="/bin/busybox.exe pscan"
alias "pstree"="/bin/busybox.exe pstree"
alias "pwdx"="/bin/busybox.exe pwdx"
alias "readlink"="/bin/busybox.exe readlink"
alias "realpath"="/bin/busybox.exe realpath"
alias "reformime"="/bin/busybox.exe reformime"
alias "renice"="/bin/busybox.exe renice"
alias "reset"="/bin/busybox.exe reset"
alias "resize"="/bin/busybox.exe resize"
alias "rev"="/bin/busybox.exe rev"
alias "rm"="/bin/busybox.exe rm"
alias "rmdir"="/bin/busybox.exe rmdir"
alias "rpm"="/bin/busybox.exe rpm"
alias "rpm2cpio"="/bin/busybox.exe rpm2cpio"
alias "run-parts"="/bin/busybox.exe run-parts"
alias "runsv"="/bin/busybox.exe runsv"
alias "runsvdir"="/bin/busybox.exe runsvdir"
alias "script"="/bin/busybox.exe script"
alias "script"="/bin/busybox.exe scriptreplay"
alias "sed"="/bin/busybox.exe sed"
alias "sendmail"="/bin/busybox.exe sendmail"
alias "seq"="/bin/busybox.exe seq"
alias "setsid"="/bin/busybox.exe setsid"
alias "setuidgid"="/bin/busybox.exe setuidgid"
alias "sha1sum"="/bin/busybox.exe sha1sum"
alias "sha256sum"="/bin/busybox.exe sha256sum"
alias "sha3sum"="/bin/busybox.exe sha3sum"
alias "sha512sum"="/bin/busybox.exe sha512sum"
alias "sleep"="/bin/busybox.exe sleep"
alias "smemcap"="/bin/busybox.exe smemcap"
alias "softlimit"="/bin/busybox.exe softlimit"
alias "sort"="/bin/busybox.exe sort"
alias "split"="/bin/busybox.exe split"
alias "start-stop-daemon"="/bin/busybox.exe start-stop-daemon"
alias "stat"="/bin/busybox.exe stat"
alias "strings"="/bin/busybox.exe strings"
alias "stty"="/bin/busybox.exe stty"
alias "sum"="/bin/busybox.exe sum"
alias "sv"="/bin/busybox.exe sv"
alias "svlogd"="/bin/busybox.exe svlogd"
alias "sync"="/bin/busybox.exe sync"
alias "sysctl"="/bin/busybox.exe sysctl"
alias "syslogd"="/bin/busybox.exe syslogd"
alias "tac"="/bin/busybox.exe tac"
alias "tail"="/bin/busybox.exe tail"
alias "tar"="/bin/busybox.exe tar"
alias "tcpsvd"="/bin/busybox.exe tcpsvd"
alias "tee"="/bin/busybox.exe tee"
alias "tftp"="/bin/busybox.exe tftp"
alias "tftpd"="/bin/busybox.exe tftpd"
alias "time"="/bin/busybox.exe time"
alias "timeout"="/bin/busybox.exe timeout"
alias "touch"="/bin/busybox.exe touch"
alias "tr"="/bin/busybox.exe tr"
alias "tty"="/bin/busybox.exe tty"
alias "ttysize"="/bin/busybox.exe ttysize"
alias "udpsvd"="/bin/busybox.exe udpsvd"
alias "uname"="/bin/busybox.exe uname"
alias "uncompress"="/bin/busybox.exe uncompress"
alias "unexpand"="/bin/busybox.exe unexpand"
alias "uniq"="/bin/busybox.exe uniq"
alias "unix2dos"="/bin/busybox.exe unix2dos"
alias "unlzma"="/bin/busybox.exe unlzma"
alias "unlzop"="/bin/busybox.exe unlzop"
alias "unxz"="/bin/busybox.exe unxz"
alias "unzip"="/bin/busybox.exe unzip"
alias "usleep"="/bin/busybox.exe usleep"
alias "uudecode"="/bin/busybox.exe uudecode"
alias "uuencode"="/bin/busybox.exe uuencode"
alias "vlock"="/bin/busybox.exe vlock"
alias "volname"="/bin/busybox.exe volname"
alias "watch"="/bin/busybox.exe watch"
alias "wc"="/bin/busybox.exe wc"
alias "which"="/bin/busybox.exe which"
alias "whoami"="/bin/busybox.exe whoami"
alias "xargs"="/bin/busybox.exe xargs"
alias "xz"="/bin/busybox.exe xz"
alias "xzcat"="/bin/busybox.exe xzcat"
alias "yes"="/bin/busybox.exe yes"
alias "zcat"="/bin/busybox.exe zcat"

alias echo="builtin echo"
alias false="builtin false"
alias printf="builtin printf"
alias pwd="builtin pwd"
alias test="builtin test"
alias true="builtin true"

alias lzmacat="/bin/busybox.exe lzcat"
alias dir="/bin/busybox.exe ls"
alias ll="/bin/busybox.exe ls -l"
alias la="/bin/busybox.exe ls -al"
alias l="/bin/busybox.exe ls -al"
alias newtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias Newtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias NewTab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias newTab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias MobaNewtab="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias new="/bin/MobaSendMsg.exe MobaXterm -newtab"
alias tab="/bin/MobaSendMsg.exe MobaXterm -newtab"

alias MobaControlAccessibility="/bin/MobaControlPanel MobaControlAccessibility"
alias MobaControlAdminTools="/bin/MobaControlPanel MobaControlAdminTools"
alias MobaControlAudio="/bin/MobaControlPanel MobaControlAudio"
alias MobaControlAudioVolume="/bin/MobaControlPanel MobaControlAudioVolume"
alias MobaControlCertificates="/bin/MobaControlPanel MobaControlCertificates"
alias MobaControlCheckDisks="/bin/MobaControlPanel MobaControlCheckDisks"
alias MobaControlCheckSystemFiles="/bin/MobaControlPanel MobaControlCheckSystemFiles"
alias MobaControlClean="/bin/MobaControlPanel MobaControlClean"
alias MobaControlColors="/bin/MobaControlPanel MobaControlColors"
alias MobaControlComputer="/bin/MobaControlPanel MobaControlComputer"
alias MobaControlDCom="/bin/MobaControlPanel MobaControlDCom"
alias MobaControlDefrag="/bin/MobaControlPanel MobaControlDefrag"
alias MobaControlDevices="/bin/MobaControlPanel MobaControlDevices"
alias MobaControlDirectX="/bin/MobaControlPanel MobaControlDirectX"
alias MobaControlDisks="/bin/MobaControlPanel MobaControlDisks"
alias MobaControlDisplay="/bin/MobaControlPanel MobaControlDisplay"
alias MobaControlDriversList="/bin/MobaControlPanel MobaControlDriversList"
alias MobaControlEvents="/bin/MobaControlPanel MobaControlEvents"
alias MobaControlFirewall="/bin/MobaControlPanel MobaControlFirewall"
alias MobaControlFolders="/bin/MobaControlPanel MobaControlFolders"
alias MobaControlFonts="/bin/MobaControlPanel MobaControlFonts"
alias MobaControlInternational="/bin/MobaControlPanel MobaControlInternational"
alias MobaControlInternet="/bin/MobaControlPanel MobaControlInternet"
alias MobaControlKeyboard="/bin/MobaControlPanel MobaControlKeyboard"
alias MobaControlMouse="/bin/MobaControlPanel MobaControlMouse"
alias MobaControlNetwork="/bin/MobaControlPanel MobaControlNetwork"
alias MobaControlNewDevice="/bin/MobaControlPanel MobaControlNewDevice"
alias MobaControlOdbc="/bin/MobaControlPanel MobaControlOdbc"
alias MobaControlPanel="/bin/MobaControlPanel"
alias MobaControlPerformances="/bin/MobaControlPanel MobaControlPerformances"
alias MobaControlPolicies="/bin/MobaControlPanel MobaControlPolicies"
alias MobaControlPrinters="/bin/MobaControlPanel MobaControlPrinters"
alias MobaControlPrograms="/bin/MobaControlPanel MobaControlPrograms"
alias MobaControlRegistry="/bin/MobaControlPanel MobaControlRegistry"
alias MobaControlRestore="/bin/MobaControlPanel MobaControlRestore"
alias MobaControlScheduler="/bin/MobaControlPanel MobaControlScheduler"
alias MobaControlSecurity="/bin/MobaControlPanel MobaControlSecurity"
alias MobaControlServices="/bin/MobaControlPanel MobaControlServices"
alias MobaControlShares="/bin/MobaControlPanel MobaControlShares"
alias MobaControlSignature="/bin/MobaControlPanel MobaControlSignature"
alias MobaControlStartup="/bin/MobaControlPanel MobaControlStartup"
alias MobaControlSystem="/bin/MobaControlPanel MobaControlSystem"
alias MobaControlSystemFiles="/bin/MobaControlPanel MobaControlSystemFiles"
alias MobaControlTasks="/bin/MobaControlPanel MobaControlTasks"
alias MobaControlTelephony="/bin/MobaControlPanel MobaControlTelephony"
alias MobaControlTime="/bin/MobaControlPanel MobaControlTime"
alias MobaControlUpdates="/bin/MobaControlPanel MobaControlUpdates"
alias MobaControlUsers="/bin/MobaControlPanel MobaControlUsers"
alias MobaControlUsersAdvanced="/bin/MobaControlPanel MobaControlUsersAdvanced"
alias MobaControlWindowsVersion="/bin/MobaControlPanel MobaControlWindowsVersion"
alias MobaProcessInfo="/bin/top"
alias htop="/bin/top"
alias MobaProcessInfoNoColor="/bin/top -nocolor"
alias MobaHwInfo="/bin/MobaHwInfo"
alias MobaKillTask="/bin/MobaKillTask"
alias MobaSwInfo="/bin/MobaSwInfo"
alias MobaTaskList="/bin/top"
alias MobApt="/bin/MobApt"
alias Mobapt="/bin/MobApt"
alias mobaprocessinfo="/bin/top"
alias mobaprocessinfonocolor="/bin/top -nocolor"
alias mobahwinfo="/bin/MobaHwInfo"
alias mobakilltask="/bin/MobaKillTask"
alias mobaswinfo="/bin/MobaSwInfo"
alias mobatasklist="/bin/top"
alias mobapt="/bin/MobApt"
alias top="/bin/top"
alias top-nocolor="/bin/top -nocolor"
alias ps2="/bin/top -once"
alias ps2-nocolor="/bin/top -once -nocolor"
alias TCPCapture="/bin/TCPCapture.exe"
alias XWin="/bin/XWin.exe"
alias tcpcapture="/bin/TCPCapture.exe"
alias xwin="/bin/XWin.exe"
alias apt-cyg="/bin/apt-cyg"
alias apt-get="/bin/apt-cyg"
alias ascii="/bin/ascii"
alias autossh="/bin/autossh.exe"
alias balance="/bin/balance.exe -M"
alias bc="/bin/bc.exe"
alias beep="/bin/beep.exe"
alias cfourcc="/bin/cfourcc.exe"
alias connect="/bin/connect.exe"
alias connect-proxy="/bin/connect.exe"
alias proxy-connect="/bin/connect.exe"
alias ctris="/bin/ctris.exe"
alias curl="/bin/curl.exe"
alias ninvaders="/bin/ninvaders.exe"
alias greed="/bin/greed.exe"
alias cygpath="/bin/cygpath.exe"
alias cygstart="/bin/cygstart.exe"
alias editrights="/bin/editrights.exe"
alias extract_compressed_fs="/bin/extract_compressed_fs.exe"
alias fdupes="/bin/fdupes.exe"
alias fortune="/bin/fortune"
alias ftp="/bin/ftp.exe"
alias getfacl="/bin/getfacl.exe"
alias glxgears="/bin/glxgears.exe"
alias glxinfo="/bin/glxinfo.exe"
alias Rainbowizer="/bin/Rainbowizer"
alias grep="/bin/grep.exe --colour"
alias grep.exe="/bin/grep.exe --colour"
alias egrep="/bin/grep.exe --colour -E"
alias fgrep="/bin/grep.exe --colour -F"
alias fvwm="/bin/fvwm"
alias rgrep="/bin/grep.exe --colour -r"
alias httping="/bin/httping.exe"
alias iconv="/bin/iconv.exe"
alias iperf="/bin/iperf.exe"
alias iperf2="/bin/iperf.exe"
alias iperf3="/bin/iperf3.exe"
alias launch="/bin/cygstart.exe"
alias ldd="/bin/ldd.exe"
alias makeself="/bin/makeself.sh"
alias makeself.sh="/bin/makeself.sh"
alias man="/bin/man"
alias mathomatic="/bin/mathomatic.exe"
alias mkgroup="/bin/mkgroup.exe"
alias mkpasswd="/bin/mkpasswd.exe"
alias mkshortcut="/bin/mkshortcut.exe"
alias mount="/bin/mount.exe"
alias ncdu="/bin/ncdu.exe"
alias ncftp="/bin/ftp.exe"
alias nimesweeper="/bin/nimesweeper.exe"
alias nc="/bin/nc.exe"
alias open="/bin/cygstart.exe"
alias passwd="/bin/passwd.exe"
alias paste="/bin/paste.exe"
alias png2ico="/bin/png2ico"
alias rcp="/bin/rcp.exe"
alias regtool="/bin/regtool.exe"
alias rsync="/bin/rsync.exe"
alias run="/bin/cygstart.exe"
alias setfacl="/bin/setfacl.exe"
alias setx11dpi="/bin/setx11dpi"
alias x11setdpi="/bin/setx11dpi"
alias xsetdpi="/bin/setx11dpi"
alias setxkbmap="/bin/setxkbmap.exe"
alias sh="/bin/bash.exe"
alias showkey="/bin/showkey.exe"
alias shutdown="/bin/shutdown.exe"
alias sshpass="/bin/sshpass.exe"
alias ssh-add="/bin/ssh-add.exe"
alias ssh-agent="/bin/ssh-agent.exe"
alias ssh-pkcs11-helper="/bin/ssh-pkcs11-helper.exe"
alias ssh-copy-id="/bin/ssh-copy-id"
alias strace="/bin/strace.exe"
alias sudo="/bin/cygstart.exe --action=runas"
alias sudoku="/bin/sudoku.exe"
alias umount="/bin/umount.exe"
alias vi="/bin/vim.exe"
alias vim="/bin/vim.exe"
alias waitforX="/bin/waitforX"
alias wget="/bin/wget.exe"
alias whois="/bin/whois"
alias xauth="/bin/xauth.exe"
alias xdpyinfo="/bin/xdpyinfo.exe"
alias xev="/bin/xev.exe"
alias xkbevd="/bin/xkbevd.exe"
alias xkill="/bin/xkill.exe"
alias xlsatoms="/bin/xlsatoms.exe"
alias xlsclients="/bin/xlsclients.exe"
alias xlsfonts="/bin/xlsfonts.exe"
alias xkbcomp="/bin/xkbcomp.exe"
alias xmodmap="/bin/xmodmap.exe"
alias xhost="/bin/xhost.exe"
alias xprop="/bin/xprop.exe"
alias xrdb="/bin/xrdb.exe"
alias kinit="/bin/kinit.exe"
alias klist="/bin/klist.exe"
alias lrz="/bin/lrz.exe"
alias lsz="/bin/lsz.exe"
alias rz="/bin/lrz.exe --zmodem"
alias sz="/bin/lsz.exe --zmodem"
alias rx="/bin/lrz.exe --xmodem"
alias sx="/bin/lsz.exe --xmodem"
alias rb="/bin/lrz.exe --ymodem"
alias sb="/bin/lsz.exe --ymodem"
alias minicom="/bin/minicom.exe -m -c on"
alias xminicom="/bin/minicom.exe -m -c on"
alias ascii-xfr="/bin/ascii-xfr.exe"
alias runscript="/bin/runscript.exe"



alias MobaWMIRequest="/bin/TCPCapture --wmi"
alias WMIRequest="/bin/TCPCapture --wmi"
alias mobawmirequest="/bin/TCPCapture --wmi"
alias wmirequest="/bin/TCPCapture --wmi"
alias MobaCalc="/bin/MobaCalc"
alias Mobacalc="/bin/MobaCalc"
alias mobacalc="/bin/MobaCalc"
alias MobaListOpenPorts="/bin/MobaListPorts"
alias Mobalistopenports="/bin/MobaListPorts"
alias mobalistopenports="/bin/MobaListPorts"
alias ListOpenPorts="/bin/MobaListPorts"
alias listopenports="/bin/MobaListPorts"
alias PortsInfo="/bin/MobaListPorts"
alias NetworkPortsList="/bin/MobaListPorts"
alias MobaPictureViewer="/bin/MobaPictureViewer"
alias Mobapictureviewer="/bin/MobaPictureViewer"
alias mobapictureviewer="/bin/MobaPictureViewer"
alias ShowImage="/bin/MobaPictureViewer"
alias showimage="/bin/MobaPictureViewer"
alias DisplayImage="/bin/MobaPictureViewer"
alias OpenImage="/bin/MobaPictureViewer"
alias openimage="/bin/MobaPictureViewer"
alias ViewImage="/bin/MobaPictureViewer"
alias viewimage="/bin/MobaPictureViewer"
alias PictureView="/bin/MobaPictureViewer"
alias pictureview="/bin/MobaPictureViewer"
alias PhotoView="/bin/MobaPictureViewer"
alias ImageView="/bin/MobaPictureViewer"
alias imageview="/bin/MobaPictureViewer"
alias Show="/bin/MobaPictureViewer"
alias Display="/bin/MobaPictureViewer"
alias PicView="/bin/MobaPictureViewer"
alias picview="/bin/MobaPictureViewer"
alias MobaTextEditor="/bin/MobaTextEditor"
alias Mobatexteditor="/bin/MobaTextEditor"
alias mobatexteditor="/bin/MobaTextEditor"
alias TextEdit="/bin/MobaTextEditor"
alias textedit="/bin/MobaTextEditor"
alias Edit="/bin/MobaTextEditor"
alias edit="/bin/MobaTextEditor"
alias OpenText="/bin/MobaTextEditor"
alias opentext="/bin/MobaTextEditor"
alias DiffFiles="/bin/MobaCompareFiles"
alias difffiles="/bin/MobaCompareFiles"
alias MobaDiffFiles="/bin/MobaCompareFiles"
alias Mobadifffiles="/bin/MobaCompareFiles"
alias mobadifffiles="/bin/MobaCompareFiles"
alias CompareFiles="/bin/MobaCompareFiles"
alias FilesDiff="/bin/MobaCompareFiles"
alias filesdiff="/bin/MobaCompareFiles"
alias FilesCompare="/bin/MobaCompareFiles"
alias TextDiff="/bin/MobaCompareFiles"
alias Textdiff="/bin/MobaCompareFiles"
alias textdiff="/bin/MobaCompareFiles"
alias MobaTextDiff="/bin/MobaCompareFiles"
alias Mobatextdiff="/bin/MobaCompareFiles"
alias mobatextdiff="/bin/MobaCompareFiles"
alias DiffFolders="/bin/MobaCompareFolders"
alias difffolders="/bin/MobaCompareFolders"
alias MobaDiffFolders="/bin/MobaCompareFolders"
alias Mobadifffolders="/bin/MobaCompareFolders"
alias mobadifffolders="/bin/MobaCompareFolders"
alias MobaFoldersDiff="/bin/MobaCompareFolders"
alias mobafoldersdiff="/bin/MobaCompareFolders"
alias CompareFolders="/bin/MobaCompareFolders"
alias comparefolders="/bin/MobaCompareFolders"
alias FoldersDiff="/bin/MobaCompareFolders"
alias foldersdiff="/bin/MobaCompareFolders"
alias FoldersCompare="/bin/MobaCompareFolders"
alias DirectoriesCompare="/bin/MobaCompareFolders"
alias cmd="/bin/conin.exe cmd"
alias cmd.exe="/bin/conin.exe cmd"
alias ps="/bin/ps.exe -W"
alias ps.exe="/bin/ps.exe -W"
alias ifconfig="TCPCapture --ifconfig"
alias kill="/bin/kill.exe -f"
alias killX="/bin/killX"
alias kill.exe="/bin/kill.exe -f"
alias reboot="/bin/shutdown.exe -f -r now"
alias halt="/bin/shutdown.exe -f -s now"
alias help="/bin/help"
alias about="open http://mobaxterm.mobatek.net/download.html"
alias telnetd="/etc/init.d/telnetd"
alias ftpd="/etc/init.d/ftpd"
alias lscolors="/bin/lscolors"

function microcom {
  [ "$1" == "-s" ] && COMPORT=" on \033[36m$3\033[0m" || COMPORT="\033[0m"
  echo -e "\033[31mLaunching microcom serial connection$COMPORT.\n\033[31mPress Ctrl+X to exit.\033[0m"
  /bin/busybox.exe microcom "$@"
}

function ssh-keygen {
  [ -e "/home/mobaxterm/README.txt" ] && cat "/home/mobaxterm/README.txt"
  /bin/ssh-keygen.exe "$@"
}

function zless {
  /bin/busybox.exe gunzip -c "$@" | less
}

function vless {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function less-syntax {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function view {
  /bin/vim.exe -R -u /etc/vimrc.less -c 'set nomod nolist' "$@"
}

function services-status {
  for i in `ls /etc/init.d/`; do /etc/init.d/$i status; done
}

function zmore {
  /bin/busybox.exe gunzip -c "$@" | more
}

function bzless {
  /bin/busybox.exe bunzip2 -c "$@" | less
}

function bzmore {
  /bin/busybox.exe bunzip2 -c "$@" | more
}

alias ssh="/bin/ssh.exe"
alias  "ssh-nocompression"="/bin/ssh.exe -o Compression=no"
alias  "ssh-noencryption"="/bin/ssh.exe -o UseRsh=yes"
alias scp="([ -n "${KRB5_CONFIG}" ] && [ -e "${KRB5_CONFIG}" ] && /bin/scp.exe -S /bin/_kssh.exe -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes) || /bin/scp.exe -S /bin/_ssh.exe"
alias sftp="([ -n "${KRB5_CONFIG}" ] && [ -e "${KRB5_CONFIG}" ] && /bin/sftp.exe -S /bin/_kssh.exe -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes) || /bin/sftp.exe -S /bin/_ssh.exe"

function telnet {
  echo -ne "\0033]2;$@\a"
  /bin/telnet.exe "$@"
}

function rsh {
  echo -ne "\0033]2;$@\a"
  /bin/rsh.exe "$@"
}

function rlogin {
  echo -ne "\0033]2;$1\a"
  /bin/rlogin.exe "$@"
}

function mcedit {
  /bin/mc.exe --edit=$@
}

function service {
  if [ -z "$1" ]; then
    services-status
  else
    /etc/init.d/"$@"
  fi
}

function dosconvert() {
  CP1="`cat /proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/OEMCP`"
  CP2="${LANG##*.}"
  if iconv -l | grep -q "CP$CP1" >/dev/null 2>/dev/null && iconv -l | grep -q "$CP2" >/dev/null 2>/dev/null; then
    "$@" | iconv -s -c -t $CP2 -f CP$CP1
  else
    "$@"
  fi
}

alias ping="dosconvert ping.exe"
alias ipconfig="dosconvert ipconfig.exe"
alias tracert="dosconvert tracert.exe"
alias netstat="dosconvert netstat.exe"
alias route="dosconvert route.exe"
alias arp="dosconvert arp.exe"
alias nbtstat="dosconvert nbtstat.exe"
alias netsh="dosconvert netsh.exe"



function ToolDisabled {
  echo -e "\033[31mSorry: $1 has been disabled by your System Administrator.\033[0m"
  echo
}
function ToolNotIncluded {
  if ls "/bin/$1" >/dev/null 2>/dev/null || ls "/bin/$1.exe" >/dev/null 2>/dev/null; then
    progname="$1"
    unalias "$progname"
    shift
    if [ "$1" == "-si" ] && [ -n "$2" ]; then
      shift
      shift
    fi
    "$progname" "$@"
  else
    echo -e "\033[31mSorry: $1 is not included in this version of MobaXterm.\033[0m
    
    You can check online if you find a \033[36m$1\033[0m plugin for MobaXterm
    by ctrl+clicking here: \033[35m\033[4mhttp://mobaxterm.mobatek.net\033[0m

    You can also try to install \033[36m$1\033[0m directly
    by using the \033[35mapt-get install $1\033[0m command

    If you need a custom version of MobaXterm that includes \033[36m$1\033[0m,
    do not hesitate to ask us for a quotation: \033[35m\033[4mmailto:contact@mobatek.net\033[0m
    "
    if [ "$2" == "-si" ] && [ -n "$3" ]; then
      echo -e "Starting \033[32m$3\033[0m instead..."
      NEWOPTS=("$@")
      unset NEWOPTS[0]
      unset NEWOPTS[1]
      unset NEWOPTS[2]
      $3 "${NEWOPTS[@]}"
      unset NEWOPTS
    fi
  fi
}

alias nedit="ToolNotIncluded nedit -si MobaTextEditor"
alias mc="ToolNotIncluded mc"
alias gvim="ToolNotIncluded gvim -si MobaTextEditor"
alias emacs="ToolNotIncluded emacs -si MobaTextEditor"
alias emacs-w32="ToolNotIncluded emacs-w32 -si MobaTextEditor"
alias xemacs="ToolNotIncluded xemacs -si MobaTextEditor"
alias kate="ToolNotIncluded kate -si MobaTextEditor"
alias kwrite="ToolNotIncluded kwrite -si MobaTextEditor"
alias gedit="ToolNotIncluded gedit -si MobaTextEditor"
alias kdiff="ToolNotIncluded kdiff -si MobaCompareFiles"
alias gphoto="ToolNotIncluded gphoto -si MobaPictureViewer"
alias kuickshow="ToolNotIncluded kuickshow -si MobaPictureViewer"
alias showimg="ToolNotIncluded showimg -si MobaPictureViewer"
alias perl="ToolNotIncluded perl"
alias python="ToolNotIncluded python"
alias lua="ToolNotIncluded lua"
alias ruby="ToolNotIncluded ruby"
alias texmacs="ToolNotIncluded texmacs"
alias lyx="ToolNotIncluded lyx"
alias tex="ToolNotIncluded teX"
alias latex="ToolNotIncluded latex"
alias make="ToolNotIncluded make"
alias gcc="ToolNotIncluded gcc"
alias g++="ToolNotIncluded g++"
alias g77="ToolNotIncluded g77"
alias gpc="ToolNotIncluded gpc"
alias gcj="ToolNotIncluded gcj"
alias konqueror="ToolNotIncluded konqueror"
alias nautilus="ToolNotIncluded nautilus"
alias pcmanfm="ToolNotIncluded pcmanfm"
alias zsh="ToolNotIncluded zsh"
alias ksh="ToolNotIncluded ksh"
alias xclock="ToolNotIncluded xclock"
alias xeyes="ToolNotIncluded xeyes"
alias afio="ToolNotIncluded afio -si cpio"
alias zip="ToolNotIncluded zip"
alias cdrecord="ToolNotIncluded cdrecord"
alias autoconf="ToolNotIncluded autoconf"
alias automake="ToolNotIncluded automake"
alias strip="ToolNotIncluded strip"
alias cvs="ToolNotIncluded cvs"
alias svn="ToolNotIncluded svn"
alias ddd="ToolNotIncluded ddd"
alias gdb="ToolNotIncluded gdb"
alias nasm="ToolNotIncluded nasm"
alias hexedit="ToolNotIncluded hexedit"
alias screen="ToolNotIncluded screen"
alias convert="ToolNotIncluded convert"
alias display="ToolNotIncluded display"
alias gv="ToolNotIncluded gv"
alias gs="ToolNotIncluded gs"
alias ghostscript="ToolNotIncluded ghostscript"
alias ploticus="ToolNotIncluded ploticus"
alias plotutils="ToolNotIncluded plotutils"
alias grace="ToolNotIncluded grace"
alias xfig="ToolNotIncluded xfig"
alias expect="ToolNotIncluded expect"
alias email="ToolNotIncluded email"
alias octave="ToolNotIncluded octave"
alias orpie="ToolNotIncluded orpie"
alias singular="ToolNotIncluded singular"
alias ctorrent="ToolNotIncluded ctorrent"
alias geoip="ToolNotIncluded geoip"
alias httptunnel="ToolNotIncluded httptunnel"
alias lftp="ToolNotIncluded lftp"
alias zsync="ToolNotIncluded zsync"
alias pdftk="ToolNotIncluded pdftk"
alias tetex="ToolNotIncluded tetex"
alias aspell="ToolNotIncluded aspell"
alias a2ps="ToolNotIncluded a2ps"
alias multitail="ToolNotIncluded multitail -si tail"
alias file="ToolNotIncluded file"
alias wput="ToolNotIncluded wput"
alias lynx="ToolNotIncluded lynx"
alias links="ToolNotIncluded links"
alias tcpdump="ToolNotIncluded tcpdump -si TCPCapture"
alias wireshark="ToolNotIncluded wireshark -si TCPCapture"
alias ethereal="ToolNotIncluded ethereal -si TCPCapture"
alias xcalc="ToolNotIncluded xcalc -si MobaCalc"
alias gcalc="ToolNotIncluded gcalc -si MobaCalc"
alias kcalc="ToolNotIncluded kcalc -si MobaCalc"


alias path='echo $PATH'
alias cgrep='grep --color=always'
alias lsd='ls -d */'
alias lll='ls -la | less'
alias md='mkdir'
alias ..='cd ..'
alias ...='cd ../..'
alias path='echo -e ${PATH//:/\\n}'
alias removeemptylines="sed -i -e '/^$/d'"
alias tree="find . | sed 's/[^/]*\//|   /g;s/| *\([^| ]\)/+--- \1/'"
alias clr="clear; pwd; ls -lrth"
alias title="xtitle"
alias settitle="xtitle"
alias settabtitle="xtitle"
alias tabtitle="xtitle"
function cl { cd $* && ls; }
function xtitle { builtin echo -en  "\e]0;$*\a"; }
function extract() {
  if [ -z "$1" ]; then
    echo "Usage: extract <archive_to_extract>"
  elif [ -f $1 ]; then
    case $1 in
      *.tar.bz2)   tar -xvjf $1;;
      *.tar.gz)    tar -xvzf $1;;
      *.tar.xz)    tar -xvJf $1;;
      *.bz2)       bunzip2 $1;;
      *.gz)        gunzip $1;;
      *.xz)        unxz $1;;
      *.lzma)      unlzma $1;;
      *.tar)       tar -xvf $1;;
      *.tbz2)      tar -xvjf $1;;
      *.tgz)       tar -xvzf $1;;
      *.txz)       tar -xvJf $1;;
      *.zip)       unzip $1;;
      *.Z)         uncompress $1;;
      *)           echo "'$1' cannot be extracted via >extract<";;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
if [ ! -e "/etc/ssh_agent_env.sh" ]; then
  ls -al /bin/ssh-pageant.exe >/dev/null 2>/dev/null
  ls -al /bin/ssh-pageant.exe >/dev/null 2>/dev/null
  /bin/ssh-pageant.exe > /etc/ssh_agent_env.sh
  /bin/busybox.exe chmod 777 /etc/ssh_agent_env.sh
  . /etc/ssh_agent_env.sh >/dev/null 2>&1
else
  . /etc/ssh_agent_env.sh >/dev/null 2>&1
fi
